Allow other accounts to publish to SNS topics
wellcometrust/terraform-modules pull request #176
Opened 2020-01-14 15:56 UTC by jamieparkinson

Required for https://github.com/wellcometrust/platform/issues/4163

2020-01-14 15:57 UTC, jamieparkinson commented on sns/cross_account_topic_policy.tf
> +    : (local.has_cross_account_pubs
This nonsense is to overcome the lack of conditional blocks and/or support for an empty list of Principals

2020-01-14 16:01 UTC, alexwlchan requested changes
Can we break up that monster conditional with some locals to make it clearer what it's doing?

2020-01-14 16:01 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +    : (local.has_cross_account_pubs
Could there be a comment explaining it?

2020-01-14 16:01 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +  policy = "${local.has_cross_account_subs && local.has_cross_account_subs
Why are you `&&`'ing a local with itself?

2020-01-14 16:01 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +    : (local.has_cross_account_pubs
FWIW, we tend to break up this stuff with judicious use of locals.

2020-01-14 16:02 UTC, jamieparkinson commented on sns/cross_account_topic_policy.tf
> +  policy = "${local.has_cross_account_subs && local.has_cross_account_subs
because bad at typing 🙃

2020-01-14 16:16 UTC, alexwlchan reviewed
A couple more suggestions for increased clarity.

2020-01-14 16:16 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +  has_cross_account_pubs = "${length(var.cross_account_publication_ids) > 0}"
Let's increase the difference between these variables too:

```
locals {
  has_cross_account_subscriptions = ...
  has_cross_account_publications = ...
```

2020-01-14 16:16 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +data "aws_iam_policy_document" "cross_account_sns_topic_policy_publications" {
for consistency:

```suggestion
data "aws_iam_policy_document" "cross_account_sns_topic_policy_publications_only" {
```

2020-01-14 16:16 UTC, alexwlchan commented on sns/cross_account_topic_policy.tf
> +data "aws_iam_policy_document" "cross_account_sns_topic_policy_subscriptions" {
for consistency:

```suggestion
data "aws_iam_policy_document" "cross_account_sns_topic_policy_subscriptions_only" {
```

2020-01-15 10:14 UTC, alexwlchan approved these changes
One suggestion on the changelog, otherwise looks good.

2020-01-15 10:14 UTC, alexwlchan commented on RELEASE.md
> +Add ability to specify accounts which can publish to an SNS topic
How about:

> Allow AWS accounts to publish to an SNS topic in a different account. Use the `cross_account_publication_ids` parameter to the `sns` module.

2020-01-15 10:22 UTC, merged